name: insigh
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.00+00

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.1.3
  firebase_core: ^2.3.0
  cloud_firestore: ^4.1.0
  firebase_storage: ^11.0.6
  firebase_messaging: ^14.1.1
  firebase_analytics: ^10.0.6
  firebase_crashlytics: ^3.0.6
  flutter_local_notifications: ^12.0.4
  provider: ^6.0.3
  path_provider: ^2.0.12
  hive: ^2.0.4
  get: ^4.6.5
  dio: ^4.0.6
  flutter_spinkit: ^5.1.0
  loading_animations: ^2.2.0
  modal_bottom_sheet: ^2.0.1
  google_sign_in: ^5.3.2
  sign_in_with_apple: ^4.0.0
  package_info_plus: ^3.0.2
  flutter_animated_dialog: ^2.0.1
  flutter_styled_toast: ^2.1.3
  flutter_windowmanager: ^0.2.0
  url_launcher: ^6.1.4
  uuid: ^3.0.4
  shimmer: ^2.0.0
  introduction_screen: ^3.0.0
  json_annotation: ^4.0.0
  flutter_icons:
    git:
      url: https://github.com/adarsh-technocrat/flutter-icons.git
      branch: null-safety-migration
  dotted_border: ^2.0.0+1
  share_plus: ^6.3.0
  hexcolor: ^3.0.1
#  purchases_flutter: ^4.0.0
  carousel_slider: ^4.0.0
  pull_to_refresh: ^2.0.0
  image_picker: ^0.8.5+3
  youtube_player_iframe: ^3.0.4
  youtube_parser: ^2.0.0
  smooth_star_rating_null_safety: ^1.0.4+2
  blurrycontainer: ^1.0.2
  toggle_switch: ^2.0.1
  cached_network_image: ^3.2.0
  image_cropper: ^3.0.0
  flutter_image_compress: ^1.1.0
  change_case: ^1.0.2
  flutter_svg: ^1.1.6
  timeago_flutter: ^1.1.0
  flutter_native_splash: ^2.2.8
  flutter_dotenv: ^5.0.2
  cool_dropdown: ^1.4.2
  configurable_expansion_tile_null_safety: ^3.1.1
  fwfh_webview: ^0.6.2+5
  custom_navigation_bar: ^0.8.2
  avatar_glow: ^2.0.2
  firebase_dynamic_links:
  easy_image_viewer: ^1.2.0
  in_app_update: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.4
  build_runner: ^2.0.4

  #flutter packages pub run flutter_launcher_icons:main
  flutter_launcher_icons: ^0.11.0
flutter_icons:
  image_path: "assets/icon/icon.png"
  android: true
  remove_alpha_ios: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - .env
